### ISSUE TITLE
The java files cannot be opened in Processing 2

### ISSUE THREAD

**Issue by ecargnfx** [dmk12/Visualiser-of-Emotions-EEG#1]
Is this still working? I have Emotive Epoc+ and Processing, but cannot open any of the files. Can you explain how to get your program running?

**Comment by dmk12** [comment]
Let me just start by saying that I haven’t looked at this code for 3 years, and things must have changed quite a lot since then.
However, you should be able to run the app using Eclipse https://eclipse.org/downloads/, as long as you have the **Emotive EDK library** installed on your machine. 
I had a developer SDK while working on this project, but it was a paid edition so I wasn’t able to distribute it with this project. Here is a link to the community edition https://github.com/Emotiv/community-sdk/tree/master/bin, hope it works. I noticed they only support Win and Linux, so if you have a Mac it might be a blocker.

So, to run the project in Eclipse:
1. Go to `File > Import Project`
2. Browse to the project directory, select the EmoApp folder and import it
3. Highlight the project in the Package Explorer, right click or press the little black arrow beside the green Play icon in top menu
<img width="33" alt="screen shot 2016-11-30 at 23 22 53" src="https://cloud.githubusercontent.com/assets/2589523/20775646/f5dfca9e-b753-11e6-8e0c-2e5bc6e6346f.png">

4. Select `Run as > Java Applet`, and it should start up
<img width="426" alt="screen shot 2016-11-30 at 23 04 38" src="https://cloud.githubusercontent.com/assets/2589523/20775449/e9d62be0-b752-11e6-852b-04675bb4bfae.png">


If you see the following error: `Exception in thread "Animation Thread" java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Unable to load library 'edk': dlopen(libedk.dylib, 9): image not found`
it means you don’t have the EDK installed, in which case please follow instructions above.

Hope this works!
